# Generated by Django 5.2.1 on 2025-05-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='surname',
            new_name='profession',
        ),
    ]
