# Generated by Django 5.2.1 on 2025-05-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_rename_surname_worker_profession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
