# Generated by Django 5.2.1 on 2025-05-11 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp1.department'),
        ),
    ]
